endpoint: https://my-jet.atlassian.net/
user: Aaron Brewbaker
login: aaron.brewbaker@jet.com
editor: nvim
custom-commands:
  - name: mine
    help: display issues assigned to me
    script: |-
      jira list --query "resolution = unresolved and assignee=currentuser() ORDER BY created"

  - name: release
    help: display tickets in given fix version
    args:
      - name: fixversion
        required: true
    script: |-
      jira list --query "fixversion = {{args.fixversion}}"
